<?php

namespace Database\Seeders;

use App\Models\Colonia;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ColoniaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $colonias = [

            [	'nombre' =>	'San Cristóbal Centro'	,	'cp' =>	'55000'	]	,
[	'nombre' =>	'Ecatepec Centro'	,	'cp' =>	'55000'	]	,
[	'nombre' =>	 'La Cruz de San Cristóbal'	,	'cp' =>	'55000'	]	,
[	'nombre' =>	'Bonito Arboledas'	,	'cp' =>	'55010'	]	,
[	'nombre' =>	'Privada de Ecatepec'	,	'cp' =>	'55010'	]	,
[	'nombre' =>	'Los Lirios'	,	'cp' =>	'55010'	]	,
[	'nombre' =>	'Camino Nacional'	,	'cp' =>	'55010'	]	,
[	'nombre' =>	'Guadalupe Victoria'	,	'cp' =>	'55010'	]	,
[	'nombre' =>	'Ampliación Guadalupe Victoria'	,	'cp' =>	'55010'	]	,
[	'nombre' =>	'Villa Esmeralda'	,	'cp' =>	'55010'	]	,
[	'nombre' =>	'Pozo de la Pila'	,	'cp' =>	'55010'	]	,
[	'nombre' =>	'El Progreso de Guadalupe Victoria'	,	'cp' =>	'55010'	]	,
[	'nombre' =>	'Rancho Victoria II'	,	'cp' =>	'55010'	]	,
[	'nombre' =>	'Barrio Nuevo Tultitlán'	,	'cp' =>	'55010'	]	,
[	'nombre' =>	'Rancho Victoria'	,	'cp' =>	'55010'   	]	,
[	'nombre' =>	'El Obraje (Diamante)'	,	'cp' =>	'55010'   	]	,
[	'nombre' =>	'Mathzi II'	,	'cp' =>	'55010'  	]	,
[	'nombre' =>	'Mathzi I'	,	'cp' =>	'55010'   	]	,
[	'nombre' =>	'El Diamante'	,	'cp' =>	'55010'   	]	,
[	'nombre' =>	'Las Piedras'	,	'cp' =>	'55010'   	]	,
[	'nombre' =>	'El Manchon'	,	'cp' =>	'55010'  	]	,
[	'nombre' =>	'Bonito las Flores'	,	'cp' =>	'55010'   	]	,
[	'nombre' =>	'Mathzi III'	,	'cp' =>	'55010'  	]	,
[	'nombre' =>	'Parque Residencial Coacalco'	,	'cp' =>	'55014'   	]	,
[	'nombre' =>	'La Joya'	,	'cp' =>	'55016'  	]	,
[	'nombre' =>	'Tío Marin'	,	'cp' =>	'55016'   	]	,
[	'nombre' =>	'Guadalupe Victoria'	,	'cp' =>	'55016'  	]	,
[	'nombre' =>	'Tía Joaquina'	,	'cp' =>	'55016'  	]	,
[	'nombre' =>	'Villas de la Joya'	,	'cp' =>	'55016'  	]	,
[	'nombre' =>	'Torres de Altavista'	,	'cp' =>	'55016'   	]	,
[	'nombre' =>	'Mesa de los Leones'	,	'cp' =>	'55016'  	]	,
[	'nombre' =>	'El Tejocote'	,	'cp' =>	'55017'   	]	,
[	'nombre' =>	'FOVISSSTE (José María Morelos y Pavón)'	,	'cp' =>	'55018'  	]	,
[	'nombre' =>	'Granja el Rosal'	,	'cp' =>	'55018'   	]	,
[	'nombre' =>	'Ecatepec 2000'	,	'cp' =>	'55018'  	]	,
[	'nombre' =>	'San Carlos'	,	'cp' =>	'55018'   	]	,
[	'nombre' =>	'La Monera'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'Misión de los 40'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'Panitzin'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'Sergio Méndez Arceo'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'Boulevares de San Cristóbal'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'El Calvario'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'Boulevares la Nacional'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'Tierra Blanca'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'Ex-Hacienda Jauregui'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'La Monera'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'Unidad Magisterial Eva Samano'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'10 de Abril'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'Bosques de San Javier'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'El Terremote'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'Martell'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'Bursaab'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'Plazas Ecatepec'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'Residencial San Cristóbal'	,	'cp' =>	'55020'   	]	,
[	'nombre' =>	'Tierra Blanca Segunda Sección (Ejido Ecatepec)'	,	'cp' =>	'55020'  	]	,
[	'nombre' =>	'Los Héroes Ecatepec Sección I'	,	'cp' =>	'55023'   	]	,
[	'nombre' =>	'Los Héroes Ecatepec Sección III'	,	'cp' =>	'55023'  	]	,
[	'nombre' =>	'Los Héroes Ecatepec Sección II'	,	'cp' =>	'55023'   	]	,
[	'nombre' =>	'Los Héroes Ecatepec Sección IV'	,	'cp' =>	'55023'  	]	,
[	'nombre' =>	'Ejidos de San Cristóbal'	,	'cp' =>	'55024'   	]	,
[	'nombre' =>	'El Carmen'	,	'cp' =>	'55024'  	]	,
[	'nombre' =>	'Ejidal Emiliano Zapata'	,	'cp' =>	'55024'   	]	,
[	'nombre' =>	'San Benjamin'	,	'cp' =>	'55025'  	]	,
[	'nombre' =>	'Santa Águeda'	,	'cp' =>	'55025'   	]	,
[	'nombre' =>	'Los Sauces'	,	'cp' =>	'55025'  	]	,
[	'nombre' =>	'Galaxia Ecatepec'	,	'cp' =>	'55025'   	]	,
[	'nombre' =>	'Ampliación el Carmen'	,	'cp' =>	'55025'  	]	,
[	'nombre' =>	'El Árbol'	,	'cp' =>	'55027'   	]	,
[	'nombre' =>	'La Huerta'	,	'cp' =>	'55027'   	]	,
[	'nombre' =>	'Vista Hermosa'	,	'cp' =>	'55028'   	]	,
[	'nombre' =>	'Granjas Ecatepec 1a Sección'	,	'cp' =>	'55029'   	]	,
[	'nombre' =>	'Granjas Ecatepec 2a Sección'	,	'cp' =>	'55029'   	]	,
[	'nombre' =>	'Ehécatl (Paseos de Ecatepec)'	,	'cp' =>	'55029'   	]	,
[	'nombre' =>	'San Andrés Ejidos'	,	'cp' =>	'55029'   	]	,
[	'nombre' =>	'San Francisco de Asís'	,	'cp' =>	'55029'   	]	,
[	'nombre' =>	'Laguna del Rey'	,	'cp' =>	'55029'   	]	,
[	'nombre' =>	'Luis Donaldo Colosio'	,	'cp' =>	'55029'   	]	,
[	'nombre' =>	'Potrero de Rey'	,	'cp' =>	'55029'   	]	,
[	'nombre' =>	'Abel Martínez Montañez'	,	'cp' =>	'55029'   	]	,
[	'nombre' =>	'Playa Golondrinas'	,	'cp' =>	'55029'   	]	,
[	'nombre' =>	'Golondrinas'	,	'cp' =>	'55029'   	]	,
[	'nombre' =>	'Independencia'	,	'cp' =>	'55029'  	]	,
[	'nombre' =>	'Ampliación Progreso Guadalupe Victoria'	,	'cp' =>	'55029'  	]	,
[	'nombre' =>	'Colinas de Ecatepec'	,	'cp' =>	'55030'   	]	,
[	'nombre' =>	'Chula Vista'	,	'cp' =>	'55030'  	]	,
[	'nombre' =>	'Doce de Diciembre'	,	'cp' =>	'55030'   	]	,
[	'nombre' =>	'Tata Félix'	,	'cp' =>	'55030'  	]	,
[	'nombre' =>	'Hogares Marla'	,	'cp' =>	'55030'   	]	,
[	'nombre' =>	'Izcalli Ecatepec'	,	'cp' =>	'55030'  	]	,
[	'nombre' =>	'Ampliación Izcalli Ecatepec Tata Félix'	,	'cp' =>	'55030'   	]	,
[	'nombre' =>	'La Curiela'	,	'cp' =>	'55030'  	]	,
[	'nombre' =>	'La Mora'	,	'cp' =>	'55030'   	]	,
[	'nombre' =>	'La Panorámica'	,	'cp' =>	'55036'  	]	,
[	'nombre' =>	'El Capulín'	,	'cp' =>	'55037'   	]	,
[	'nombre' =>	'Floresta'	,	'cp' =>	'55038'  	]	,
[	'nombre' =>	'Las Palmas II'	,	'cp' =>	'55039'   	]	,
[	'nombre' =>	'Las Palmas I'	,	'cp' =>	'55039'   	]	,
[	'nombre' =>	'Álamos de San Cristóbal'	,	'cp' =>	'55040'   	]	,
[	'nombre' =>	'Boulevares Impala'	,	'cp' =>	'55040'   	]	,
[	'nombre' =>	'Casas Coloniales Morelos'	,	'cp' =>	'55040'   	]	,
[	'nombre' =>	'Fuentes de San Cristóbal'	,	'cp' =>	'55040'   	]	,
[	'nombre' =>	'Hogares Mexicanos'	,	'cp' =>	'55040'   	]	,
[	'nombre' =>	'Jardines de Ecatepec'	,	'cp' =>	'55040'   	]	,
[	'nombre' =>	'La Propiedad'	,	'cp' =>	'55040'  	]	,
[	'nombre' =>	'La Propiedad'	,	'cp' =>	'55040'   	]	,
[	'nombre' =>	'Renovación Jajalpa'	,	'cp' =>	'55040'   	]	,
[	'nombre' =>	'San Juan Alcahuacan'	,	'cp' =>	'55040'   	]	,
[	'nombre' =>	'El Salado'	,	'cp' =>	'55050'   	]	,
[	'nombre' =>	'La Pradera'	,	'cp' =>	'55050'   	]	,
[	'nombre' =>	'Vivienda del Taxista'	,	'cp' =>	'55050'   	]	,
[	'nombre' =>	'Adolfo Ruiz Cortines'	,	'cp' =>	'55050'   	]	,
[	'nombre' =>	'Aquiles Serdán'	,	'cp' =>	'55050'   	]	,
[	'nombre' =>	'Bosques de Ecatepec'	,	'cp' =>	'55050'   	]	,
[	'nombre' =>	'Residencial Fuentes de Ecatepec'	,	'cp' =>	'55050'   	]	,
[	'nombre' =>	'Gustavo Baz Prada'	,	'cp' =>	'55050'   	]	,
[	'nombre' =>	'Izcalli Jardines'	,	'cp' =>	'55050'   	]	,
[	'nombre' =>	'Nuevo Diaz Ordaz'	,	'cp' =>	'55050'   	]	,
[	'nombre' =>	'San Martín de Porres'	,	'cp' =>	'55050'   	]	,
[	'nombre' =>	'Rinconada San Martín'	,	'cp' =>	'55050'   	]	,
[	'nombre' =>	'Hacienda Santa María'	,	'cp' =>	'55050'  	]	,
[	'nombre' =>	'Ex Rancho Jajalpa'	,	'cp' =>	'55050'   	]	,
[	'nombre' =>	'Rancho Jajalpa'	,	'cp' =>	'55050'   	]	,
[	'nombre' =>	'Pirules de Villancico 2a Sección'	,	'cp' =>	'55050'   	]	,
[	'nombre' =>	'La Veleta'	,	'cp' =>	'55055'   	]	,
[	'nombre' =>	'Jardines de los Báez 1a Sección'	,	'cp' =>	'55055'   	]	,
[	'nombre' =>	'Jardines de los Báez 2a Sección'	,	'cp' =>	'55055'   	]	,
[	'nombre' =>	'Jardines de los Báez 3a Sección'	,	'cp' =>	'55055'   	]	,
[	'nombre' =>	'Llano de los Báez'	,	'cp' =>	'55055'   	]	,
[	'nombre' =>	'Llano de los Báez'	,	'cp' =>	'55055'  	]	,
[	'nombre' =>	'Ampliación Llano de los Báez Sección Izcalli'	,	'cp' =>	'55055'  	]	,
[	'nombre' =>	'Jubilados y Pensionados'	,	'cp' =>	'55055'   	]	,
[	'nombre' =>	'El Sol de Ecatepec'	,	'cp' =>	'55055'  	]	,
[	'nombre' =>	'Villas de Ecatepec'	,	'cp' =>	'55056'   	]	,
[	'nombre' =>	'Pirules de Villancico 1a Sección'	,	'cp' =>	'55059'  	]	,
[	'nombre' =>	'Venta de Carpio'	,	'cp' =>	'55060'   	]	,
[	'nombre' =>	'La Guadalupana'	,	'cp' =>	'55060'  	]	,
[	'nombre' =>	'Los Héroes Ecatepec Sección V'	,	'cp' =>	'55060'   	]	,
[	'nombre' =>	'Privadas de Ecatepec'	,	'cp' =>	'55060'  	]	,
[	'nombre' =>	'Ciudad Cuauhtémoc Sección Chiconautla 3000'	,	'cp' =>	'55063'   	]	,
[	'nombre' =>	'Ciudad Cuauhtémoc Sección Nopalera I y II'	,	'cp' =>	'55064'  	]	,
[	'nombre' =>	'San Isidro Atlautenco'	,	'cp' =>	'55064'   	]	,
[	'nombre' =>	'Ampliación San Isidro Atlautenco'	,	'cp' =>	'55064'  	]	,
[	'nombre' =>	'San Isidro Atlautenco'	,	'cp' =>	'55064'   	]	,
[	'nombre' =>	'Vistas de Ecatepec (Sección B)'	,	'cp' =>	'55064'  	]	,
[	'nombre' =>	'La Venta (La Guadalupana)'	,	'cp' =>	'55064'   	]	,
[	'nombre' =>	'Vistas de Ecatepec (Sección A)'	,	'cp' =>	'55064'   	]	,
[	'nombre' =>	'Joyas de Atlautenco',	'cp' =>	'55064'  	]	,
[	'nombre' =>	'Santa Cruz Venta de Carpio',		'cp' =>	'55065'   	]	,
[	'nombre' =>	'El Potrero'	,	'cp' =>	'55066'   	]	,
[	'nombre' =>	'Terremote'	,	'cp' =>	'55066'   	]	,
[	'nombre' =>	'Pirules de Bayisco'	,	'cp' =>	'55066'   	]	,
[	'nombre' =>	'Casas Reales'	,	'cp' =>	'55066'   	]	,
[	'nombre' =>	'Las Brisas'	,	'cp' =>	'55066'   	]	,
[	'nombre' =>	'Santa María Chiconautla'	,	'cp' =>	'55066'   	]	,
[	'nombre' =>	'Santo Tomás Chiconautla'	,	'cp' =>	'55066'   	]	,
[	'nombre' =>	'Zopilocalco'	,	'cp' =>	'55066'   	]	,
[	'nombre' =>	'Portal Chiconautla'	,	'cp' =>	'55066'   	]	,
[	'nombre' =>	'Campo Santo'	,	'cp' =>	'55066'   	]	,
[	'nombre' =>	'Los Ídolos'	,	'cp' =>	'55066'   	]	,
[	'nombre' =>	'Jaime Salvador'	,	'cp' =>	'55066'  	]	,
[	'nombre' =>	'La Cerca'	,	'cp' =>	'55066'   	]	,
[	'nombre' =>	'La Preciosa'	,	'cp' =>	'55066'   	]	,
[	'nombre' =>	'México Nuevo'	,	'cp' =>	'55066'   	]	,
[	'nombre' =>	'Ciudad Cuauhtémoc Sección Geo 2000'	,	'cp' =>	'55067'   	]	,
[	'nombre' =>	'Ciudad Cuauhtémoc Sección Tepoztlaco'	,	'cp' =>	'55067'   	]	,
[	'nombre' =>	'Ciudad Cuauhtémoc Sección Cuitlahuac'	,	'cp' =>	'55067'   	]	,
[	'nombre' =>	'Ciudad Cuauhtémoc Sección Embajada'	,	'cp' =>	'55067'   	]	,
[	'nombre' =>	'Ciudad Cuauhtémoc Sección Moctezuma'	,	'cp' =>	'55067'   	]	,
[	'nombre' =>	'Ciudad Cuauhtémoc Sección Quetzalcoatl'	,	'cp' =>	'55067'   	]	,
[	'nombre' =>	'Ciudad Cuauhtémoc Sección Tizoc'	,	'cp' =>	'55067'   	]	,
[	'nombre' =>	'Ciudad Cuauhtémoc Sección Tonatiuh'	,	'cp' =>	'55067'   	]	,
[	'nombre' =>	'Ciudad Cuauhtémoc Sección Xochiquetzal'	,	'cp' =>	'55067'   	]	,
[	'nombre' =>	'Los Llanetes'	,	'cp' =>	'55067'   	]	,
[	'nombre' =>	'Coyometla'	,	'cp' =>	'55067'   	]	,
[	'nombre' =>	'Niños Héroes'	,	'cp' =>	'55067'   	]	,
[	'nombre' =>	'Ciudad Cuauhtémoc Sección Tlaloc'	,	'cp' =>	'55067'   	]	,
[	'nombre' =>	'La Fortaleza'	,	'cp' =>	'55067'   	]	,
[	'nombre' =>	'Moneda de 100 Pesos'	,	'cp' =>	'55067'  	]	,
[	'nombre' =>	'Tepetzingo el Chico'	,	'cp' =>	'55067'  	]	,
[	'nombre' =>	'Ciudad Cuauhtémoc Sección Tepetzingo'	,	'cp' =>	'55067'   	]	,
[	'nombre' =>	'C.T.M. Guadalupana'	,	'cp' =>	'55067'  	]	,
[	'nombre' =>	'Tepopotla'	,	'cp' =>	'55067'   	]	,
[	'nombre' =>	'El Hoyo del Tepetate'	,	'cp' =>	'55067'  	]	,
[	'nombre' =>	'Santo Tomás Chiconautla'	,	'cp' =>	'55068'   	]	,
[	'nombre' =>	'El Hoyo'	,	'cp' =>	'55068'  	]	,
[	'nombre' =>	'Ignacio Pichardo Pagaza'	,	'cp' =>	'55068'   	]	,
[	'nombre' =>	'El Mirador'	,	'cp' =>	'55068'  	]	,
[	'nombre' =>	'La Preciosa'	,	'cp' =>	'55069'   	]	,
[	'nombre' =>	'Los Pajaritos'	,	'cp' =>	'55069'  	]	,
[	'nombre' =>	'La Garita'	,	'cp' =>	'55069'   	]	,
[	'nombre' =>	'Techachahe'	,	'cp' =>	'55069'  	]	,
[	'nombre' =>	'La Cerca'	,	'cp' =>	'55069'   	]	,
[	'nombre' =>	'Tetela'	,	'cp' =>	'55069'  	]	,
[	'nombre' =>	'El Pozo'	,	'cp' =>	'55069'   	]	,
[	'nombre' =>	'Bosques de Santo Tomás'	,	'cp' =>	'55069'  	]	,
[	'nombre' =>	'Carlos Salinas de Gortari'	,	'cp' =>	'55070'  	]	,
[	'nombre' =>	'Colonial Ecatepec'	,	'cp' =>	'55070'  	]	,
[	'nombre' =>	'19 de Septiembre'	,	'cp' =>	'55070'  	]	,
[	'nombre' =>	'Ampliación 19 de Septiembre'	,	'cp' =>	'55070'  	]	,
[	'nombre' =>	'Plan de Arroyo'	,	'cp' =>	'55070'  	]	,
[	'nombre' =>	'Jardines de Morelos Sección Cerros'	,	'cp' =>	'55070'  	]	,
[	'nombre' =>	'Jardines de Morelos Sección Elementos'	,	'cp' =>	'55070'  	]	,
[	'nombre' =>	'Jardines de Morelos Sección Flores'	,	'cp' =>	'55070'   	]	,
[	'nombre' =>	'Jardines de Morelos Sección Fuentes'	,	'cp' =>	'55070'  	]	,
[	'nombre' =>	'Jardines de Morelos Sección Islas'	,	'cp' =>	'55070'  	]	,
[	'nombre' =>	'Jardines de Morelos Sección Bosques'	,	'cp' =>	'55070'  	]	,
[	'nombre' =>	'Jardines de Morelos Sección Lagos'	,	'cp' =>	'55070'   	]	,
[	'nombre' =>	'Jardines de Morelos Sección Montes'	,	'cp' =>	'55070'  	]	,
[	'nombre' =>	'Jardines de Morelos Sección Playas'	,	'cp' =>	'55070'  	]	,
[	'nombre' =>	'Jardines de Morelos Sección Ríos'	,	'cp' =>	'55070'  	]	,
[	'nombre' =>	'Llanos de Morelos I'	,	'cp' =>	'55070'   	]	,
[	'nombre' =>	'Villas del Sol'	,	'cp' =>	'55070'  	]	,
[	'nombre' =>	'Llanos de Morelos II'	,	'cp' =>	'55070'  	]	,
[	'nombre' =>	'Sol II'	,	'cp' =>	'55070'  	]	,
[	'nombre' =>	'Julia Marin'	,	'cp' =>	'55070'   	]	,
[	'nombre' =>	'Profopec (Polígonos VII)'	,	'cp' =>	'55070'  	]	,
[	'nombre' =>	'La Purísima'	,	'cp' =>	'55074'  	]	,
[	'nombre' =>	'Mexicanos Unidos I'	,	'cp' =>	'55074'  	]	,
[	'nombre' =>	'Playas de San Juan'	,	'cp' =>	'55074'   	]	,
[	'nombre' =>	'Uprovi'	,	'cp' =>	'55074'  	]	,
[	'nombre' =>	'Viento Nuevo'	,	'cp' =>	'55074'  	]	,
[	'nombre' =>	'Los Alcatraces'	,	'cp' =>	'55074'  	]	,
[	'nombre' =>	'Los Pinos'	,	'cp' =>	'55074'   	]	,
[	'nombre' =>	'Ampliación 19 de Septiembre 1A Sección'	,	'cp' =>	'55074'  	]	,
[	'nombre' =>	'Los Cordeles'	,	'cp' =>	'55074'  	]	,
[	'nombre' =>	'Mexicanos Unidos II'	,	'cp' =>	 '55074'  	]	,
[	'nombre' =>	'Ejido de Atlautenco'	,	'cp' =>	'55074'   	]	,
[	'nombre' =>	'Jardines de Morelos 5a Sección'	,	'cp' =>	'55075'  	]	,
[	'nombre' =>	'Las Américas'	,	'cp' =>	'55076'  	]	,
[	'nombre' =>	'Arboledas de San Carlos'	,	'cp' =>	'55080'  	]	,
[	'nombre' =>	'Xochicuac I'	,	'cp' =>	'55080'   	]	,
[	'nombre' =>	'El Bosque'	,	'cp' =>	'55118'  	]	,
[	'nombre' =>	'Francisco Villa'	,	'cp' =>	'55118'   	]	,
[	'nombre' =>	'Jesús Sánchez'	,	'cp' =>	'55118'  	]	,
[	'nombre' =>	'Nuevo Laredo'	,	'cp' =>	'55118'  	]	,
[	'nombre' =>	'Xochicuac II'	,	'cp' =>	'55118'  	]	,
[	'nombre' =>	'Lomas de Ecatepec'	,	'cp' =>	'55119'   	]	,
[	'nombre' =>	'Lomas de Atzolco'	,	'cp' =>	'55119'  	]	,
[	'nombre' =>	'San Carlos'	,	'cp' =>	'55119'  	]	,
[	'nombre' =>	'El Ranchito'	,	'cp' =>	'55120'  	]	,
[	'nombre' =>	'Viveros Tulpetlac'	,	'cp' =>	'55120'  	]	,
[	'nombre' =>	'Lomas de San Carlos Zona Comunal'	,	'cp' =>	'55125'   	]	,
[	'nombre' =>	'El Potrero'	,	'cp' =>	'55125'   	]	,
[	'nombre' =>	'El Arbolito Jajalpa'	,	'cp' =>	'55126'   	]	,
[	'nombre' =>	'El Jaguey'	,	'cp' =>	'55127'   	]	,
[	'nombre' =>	'San José Jajalpa'	,	'cp' =>	'55128'   	]	,
[	'nombre' =>	'Jajalpa'	,	'cp' =>	'55129'   	]	,
[	'nombre' =>	'Las Palmas Ecatepec'	,	'cp' =>	'55129'   	]	,
[	'nombre' =>	'Los Laureles'	,	'cp' =>	'55130'   	]	,
[	'nombre' =>	'Obrera Jajalpa'	,	'cp' =>	'55130'   	]	,
[	'nombre' =>	'Jajalpa Olímpica'	,	'cp' =>	'55130'   	]	,
[	'nombre' =>	'Río Piedras'	,	'cp' =>	'55130'   	]	,
[	'nombre' =>	'Bonito Ecatepec'	,	'cp' =>	'55130'   	]	,
[	'nombre' =>	'El Pocito'	,	'cp' =>	'55130'   	]	,
[	'nombre' =>	'Ecatepec 40 Casas'	,	'cp' =>	'55130'  	]	,
[	'nombre' =>	'Villas Jajalpa'	,	'cp' =>	'55130'   	]	,
[	'nombre' =>	'Jajalpa'	,	'cp' =>	'55135'   	]	,
[	'nombre' =>	'Jardines de Cerro Gordo'	,	'cp' =>	'55137'   	]	,
[	'nombre' =>	'Los Reyes Ecatepec'	,	'cp' =>	'55138'   	]	,
[	'nombre' =>	'Río de Luz'	,	'cp' =>	'55139'   	]	,
[	'nombre' =>	'Industrias Ecatepec'	,	'cp' =>	'55140'   	]	,
[	'nombre' =>	'Tulpetlac'	,	'cp' =>	'55140'  	]	,
[	'nombre' =>	'Francisco I. Madero'	,	'cp' =>	'55146'   	]	,
[	'nombre' =>	'Villas 1o de Agosto'	,	'cp' =>	'55147'   	]	,
[	'nombre' =>	'Pro Revolución'	,	'cp' =>	'55148'   	]	,
[	'nombre' =>	'Viviendas Venta de Carpio'	,	'cp' =>	'55148'   	]	,
[	'nombre' =>	'Primero de Mayo'	,	'cp' =>	'55149'   	]	,
[	'nombre' =>	'Patrimonio Social'	,	'cp' =>	'55158'   	]	,
[	'nombre' =>	'Villa 1o de Mayo'	,	'cp' =>	'55170'   	]	,
[	'nombre' =>	'Granjas Populares Guadalupe Tulpetlac'	,	'cp' =>	'55170'   	]	,
[	'nombre' =>	'El Paraíso'	,	'cp' =>	'55170'   	]	,
[	'nombre' =>	'Ignacio L. Vallarta'	,	'cp' =>	'55176'   	]	,
[	'nombre' =>	'Industrias Tulpetlac'	,	'cp' =>	'55180'   	]	,
[	'nombre' =>	'Tolotzin I'	,	'cp' =>	'55187'   	]	,
[	'nombre' =>	'José María Morelos y Pavón Sagitario X'	,	'cp' =>	'55188'   	]	,
[	'nombre' =>	'Josefa Ortiz de Domínguez Sagitario VII'	,	'cp' =>	'55189'   	]	,
[	'nombre' =>	'Alfredo del Mazo'	,	'cp' =>	'55190'   	]	,
[	'nombre' =>	'Progreso de la Unión'	,	'cp' =>	'55200'   	]	,
[	'nombre' =>	'Joyas de Ecatepec'	,	'cp' =>	'55200'   	]	,
[	'nombre' =>	'Colonos de México (Alfredo Torres Martínez)'	,	'cp' =>	'55200'   	]	,
[	'nombre' =>	'Juan de la Barrera'	,	'cp' =>	'55200'   	]	,
[	'nombre' =>	'Ampliación Joyas de Ecatepec'	,	'cp' =>	'55210'   	]	,
[	'nombre' =>	'Sosa Ecatepec'	,	'cp' =>	'55210'   	]	,
[	'nombre' =>	'Cuchilla de la Draga'	,	'cp' =>	'55210'   	]	,
[	'nombre' =>	'El Dique'	,	'cp' =>	'55218'   	]	,
[	'nombre' =>	'Potrero Chico'	,	'cp' =>	'55220'   	]	,
[	'nombre' =>	'Valle de Ecatepec Estado de México CTM XIII'	,	'cp' =>	'55220'   	]	,
[	'nombre' =>	'Ciudad Azteca Sección Poniente'	,	'cp' =>	'55220'   	]	,
[	'nombre' =>	'Ciudad Azteca Sección Oriente'	,	'cp' =>	'55220'   	]	,
[	'nombre' =>	'Aldeas de Aragón I'	,	'cp' =>	'55230'   	]	,
[	'nombre' =>	'Aldeas de Aragón II'	,	'cp' =>	'55234'   	]	,
[	'nombre' =>	'Profopec (Polígono I)'	,	'cp' =>	'55235'   	]	,
[	'nombre' =>	'Profopec IV (Polígono IV El Cegor)'	,	'cp' =>	'55244'   	]	,
[	'nombre' =>	'José Antonio Torres'	,	'cp' =>	'55245'   	]	,
[	'nombre' =>	'La Florida (Ciudad Azteca)'	,	'cp' =>	'55246'   	]	,
[	'nombre' =>	'Josefa Ortiz de Domínguez'	,	'cp' =>	'55247'   	]	,
[	'nombre' =>	'Nuevo Paseo de San Agustín'	,	'cp' =>	'55247'   	]	,
[	'nombre' =>	'Nuevo Paseo de San Agustín 2a Secc'	,	'cp' =>	'55248'   	]	,
[	'nombre' =>	'Nuevo Paseo de San Agustín 3a Sección'	,	'cp' =>	'55249'   	]	,
[	'nombre' =>	'Olímpica 68 I'	,	'cp' =>	'55249'   	]	,
[	'nombre' =>	'Plaza de Santa Clara'	,	'cp' =>	'55260'   	]	,
[	'nombre' =>	'Vicente Coss Ramírez'	,	'cp' =>	'55264'   	]	,
[	'nombre' =>	'Ciudad y Puerto'	,	'cp' =>	'55264'   	]	,
[	'nombre' =>	'Nuevo Paseo San Agustín 3a B'	,	'cp' =>	'55264'   	]	,
[	'nombre' =>	'Laderas del Peñón'	,	'cp' =>	'55264'   	]	,
[	'nombre' =>	'INDECO Santa Clara (Campiñas de Aragón)'	,	'cp' =>	'55266'   	]	,
[	'nombre' =>	'Valle de Santiago'	,	'cp' =>	'55266'   	]	,
[	'nombre' =>	'Campiñas de Aragón'	,	'cp' =>	'55267'   	]	,
[	'nombre' =>	'Jardines de Aragón'	,	'cp' =>	'55267'   	]	,
[	'nombre' =>	'Rinconada de Aragón'	,	'cp' =>	'55267'   	]	,
[	'nombre' =>	'Tolotzin II'	,	'cp' =>	'55267'   	]	,
[	'nombre' =>	'Los Álamos'	,	'cp' =>	'55268'   	]	,
[	'nombre' =>	'Villas de Aragón'	,	'cp' =>	'55268'   	]	,
[	'nombre' =>	'Alborada de Aragón'	,	'cp' =>	'55268'   	]	,
[	'nombre' =>	'Ignacio Allende'	,	'cp' =>	'55269'   	]	,
[	'nombre' =>	'Profopec (Polígono II)'	,	'cp' =>	 '55269'   	]	,
[	'nombre' =>	'Central Michoacana'	,	'cp' =>	'55269'   	]	,
[	'nombre' =>	'16 de Septiembre'	,	'cp' =>	'55269'   	]	,
[	'nombre' =>	'Sagitario IV'	,	'cp' =>	'55270'   	]	,
[	'nombre' =>	'Profopec (Polígono V)'	,	'cp' =>	'55270'   	]	,
[	'nombre' =>	'México Colonial II'	,	'cp' =>	'55270'   	]	,
[	'nombre' =>	'Profopec (Polígono III)'	,	'cp' =>	'55270'   	]	,
[	'nombre' =>	'México Colonial I'	,	'cp' =>	'55280'   	]	,
[	'nombre' =>	'Novela Mexicana I'	,	'cp' =>	'55280'   	]	,
[	'nombre' =>	'Lázaro Cárdenas V Zona'	,	'cp' =>	'55280'   	]	,
[	'nombre' =>	'División del Norte'	,	'cp' =>	'55280'   	]	,
[	'nombre' =>	'Emiliano Zapata 1a Sección'	,	'cp' =>	'55280'   	]	,
[	'nombre' =>	'Gustavo Díaz Ordaz'	,	'cp' =>	'55284'   	]	,
[	'nombre' =>	'Granjas Valle de Guadalupe Sección B'	,	'cp' =>	'55287'   	]	,
[	'nombre' =>	'La Estrella'	,	'cp' =>	'55288'   	]	,
[	'nombre' =>	'La Popular'	,	'cp' =>	'55289'   	]	,
[	'nombre' =>	'Valle de Anáhuac Sección A'	,	'cp' =>	'55290'   	]	,
[	'nombre' =>	'Cuchilla A. Rosalesc'	,	'cp' =>	'55290'   	]	,
[	'nombre' =>	'Jardines de San Gabriel'	,	'cp' =>	'55290'   	]	,
[	'nombre' =>	'Jardines del Tepeyac'	,	'cp' =>	'55290'   	]	,
[	'nombre' =>	'Vicente Guerrero'	,	'cp' =>	'55290'   	]	,
[	'nombre' =>	'Emiliano Zapata 1a Sección A'	,	'cp' =>	'55290'   	]	,
[	'nombre' =>	'La Media Luna'	,	'cp' =>	'55294'   	]	,
[	'nombre' =>	'La Glorieta'	,	'cp' =>	'55295'   	]	,
[	'nombre' =>	'Unidad Obrero CTM XIV'	,	'cp' =>	'55295'   	]	,
[	'nombre' =>	'Códice Mendocino II'	,	'cp' =>	'55295'   	]	,
[	'nombre' =>	'Códice Mendocino I'	,	'cp' =>	'55295'   	]	,
[	'nombre' =>	'Sagitario V'	,	'cp' =>	'55296'   	]	,
[	'nombre' =>	'Ampliación Códice Mendocino'	,	'cp' =>	'55296'   	]	,
[	'nombre' =>	'Estrella de Oriente'	,	'cp' =>	'55296'   	]	,
[	'nombre' =>	'Ejercito del Trabajo II'	,	'cp' =>	'55297'   	]	,
[	'nombre' =>	'Izcalli Santa Clara'	,	'cp' =>	'55298'   	]	,
[	'nombre' =>	'Sagitario I'	,	'cp' =>	'55299'   	]	,
[	'nombre' =>	'Felipe Ángeles (Antes Sagitario II)'	,	'cp' =>	'55300'   	]	,
[	'nombre' =>	'Sagitario III'	,	'cp' =>	'55038'   	]	,
[	'nombre' =>	'Alborada'	,	'cp' =>	'55038'   	]	,
[	'nombre' =>	'La Florida'	,	'cp' =>	'55310'   	]	,
[	'nombre' =>	'Melchor Muzquiz'	,	'cp' =>	'55310'   	]	,
[	'nombre' =>	'Villas Cosmos'	,	'cp' =>	'55316'   	]	,
[	'nombre' =>	'Haciendas de Aragón'	,	'cp' =>	'55317'   	]	,
[	'nombre' =>	'Parques de Aragón'	,	'cp' =>	'55320'   	]	,
[	'nombre' =>	'Paseos de Aragón'	,	'cp' =>	'55320'   	]	,
[	'nombre' =>	'Castillos de Aragón'	,	'cp' =>	'55320'   	]	,
[	'nombre' =>	'México Independiente'	,	'cp' =>	'55320'   	]	,
[	'nombre' =>	'Petroquímica Ecatepec'	,	'cp' =>	'55330'   	]	,
[	'nombre' =>	'Ciudad Oriente'	,	'cp' =>	'55330'   	]	,
[	'nombre' =>	'CROC Aragón'	,	'cp' =>	'55330'   	]	,
[	'nombre' =>	'Fuentes de Aragón'	,	'cp' =>	'55330'   	]	,
[	'nombre' =>	'Ecatepec Federación (Mártires de Río Blanco)'	,	'cp' =>	'55330'   	]	,
[	'nombre' =>	'Poesía Mexicana'	,	'cp' =>	'55330'   	]	,
[	'nombre' =>	'Nueva Aragón'	,	'cp' =>	'55330'   	]	,
[	'nombre' =>	'Prizo I'	,	'cp' =>	'55330'   	]	,
[	'nombre' =>	'Prizo II'	,	'cp' =>	'55338'   	]	,
[	'nombre' =>	'Fernando de Alba Nezahualpilli'	,	'cp' =>	'55339'   	]	,
[	'nombre' =>	'Prizo III',	'cp' =>	'55340'   	]	,
[	'nombre' =>	'México Insurgente'	,	'cp' =>	'55340'   	]	,
[	'nombre' =>	'México Revolucionario'	,	'cp' =>	'55340'   	]	,
[	'nombre' =>	'Ciudad Amanecer'	,	'cp' =>	'55347'   	]	,
[	'nombre' =>	'Quinto Sol'	,	'cp' =>	'55348'   	]	,
[	'nombre' =>	'Sauces V'	,	'cp' =>	'55349'   	]	,
[	'nombre' =>	'Sauces II'	,	'cp' =>	'55360'   	]	,
[	'nombre' =>	'Sauces VI'	,	'cp' =>	'55360'   	]	,
[	'nombre' =>	'Sauces Coalición'	,	'cp' =>	'55369'   	]	,
[	'nombre' =>	'Novela Mexicana II'	,	'cp' =>	'55390'   	]	,
[	'nombre' =>	'Sauces I'	,	'cp' =>	'55390'   	]	,
[	'nombre' =>	'México Prehispánico I'	,	'cp' =>	'55400'   	]	,
[	'nombre' =>	'México Prehispánico II'	,	'cp' =>	'55400'   	]	,
[	'nombre' =>	'Sauces P.R.I.'	,	'cp' =>	'55400'   	]	,
[	'nombre' =>	'Emiliano Zapata 2a Secc'	,	'cp' =>	'55400'   	]	,
[	'nombre' =>	'El Chamizal'	,	'cp' =>	'55400'   	]	,
[	'nombre' =>	'Granjas Valle de Guadalupe Sección A'	,	'cp' =>	'55404'   	]	,
[	'nombre' =>	'Granjas Valle de Guadalupe Sección C'	,	'cp' =>	'55404'   	]	,
[	'nombre' =>	'Renacimiento de Aragón'	,	'cp' =>	'55404'   	]	,
[	'nombre' =>	'Valle de Aragón 3ra Sección Oriente'	,	'cp' =>	'55404'   	]	,
[	'nombre' =>	'Ampliación Valle de Aragón Sección A'	,	'cp' =>	'55404'   	]	,
[	'nombre' =>	'Valle de Aragón 3ra Sección Poniente'	,	'cp' =>	'55405'   	]	,
[	'nombre' =>	'Nuevo Valle de Aragón'	,	'cp' =>	'55407'   	]	,
[	'nombre' =>	'Renacimiento Chico'	,	'cp' =>	'55407'   	]	,
[	'nombre' =>	'Fernando Alba Ixtlaxóchitl'	,	'cp' =>	'55410'   	]	,
[	'nombre' =>	'Nezahualpilli',	'cp' =>	'55410'   	]	,
[	'nombre' =>	'Bugambilias de Aragón'	,	'cp' =>	'55410'   	]	,
[	'nombre' =>	'Arboledas de Aragón'	,	'cp' =>	'55414'   	]	,
[	'nombre' =>	'Granjas Independencia'	,	'cp' =>	'55414'   	]	,
[	'nombre' =>	'Granjas Independencia Sección A'	,	'cp' =>	'55414'   	]	,
[	'nombre' =>	'Granjas Independencia Sección B'	,	'cp' =>	'55414'   	]	,
[	'nombre' =>	'Granjas Independencia Sección C'	,	'cp' =>	'55414'   	]	,
[	'nombre' =>	'Solidaridad 90 (Mártires de Río Blanco)'	,	'cp' =>	'55414'   	]	,
[	'nombre' =>	'Av. Central CROC'	,	'cp' =>	'55414'   	]	,
[	'nombre' =>	'Lic. Pedro Ojeda Paullada'	,	'cp' =>	'55415'   	]	,
[	'nombre' =>	'Ampliación Pedro Ojeda Paullada'	,	'cp' =>	'55415'   	]	,
[	'nombre' =>	'Ampliación Nicolás Bravo'	,	'cp' =>	'55415'   	]	,
[	'nombre' =>	'Franja Valle de Guadalupe'	,	'cp' =>	'55415'   	]	,
[	'nombre' =>	'Nicolás Bravo'	,	'cp' =>	'55415'   	]	,
[	'nombre' =>	'A.S.A.'	,	'cp' =>	'55415'   	]	,
[	'nombre' =>	'Las Flores de Aragón'	,	'cp' =>	'55416'   	]	,
[	'nombre' =>	'Héroes de Granaditas'	,	'cp' =>	'55416'   	]	,
[	'nombre' =>	'Ejercito del Trabajo III'	,	'cp' =>	'55416'   	]	,
[	'nombre' =>	'Ejercito del Trabajo I'	,	'cp' =>	'55416'   	]	,
[	'nombre' =>	'Piedra Grande'	,	'cp' =>	'55416'   	]	,
[	'nombre' =>	'Benito Juárez Xalostoc Norte'	,	'cp' =>	'55416'   	]	,
[	'nombre' =>	'Benito Juárez La Mesa'	,	'cp' =>	'55417'   	]	,
[	'nombre' =>	'Cuauhtémoc Xalostoc'	,	'cp' =>	'55418'   	]	,
[	'nombre' =>	'San Pedro Xalostoc'	,	'cp' =>	'55418'   	]	,
[	'nombre' =>	'Ampliación San Pedro Xalostoc'	,	'cp' =>	'55418'   	]	,
[	'nombre' =>	'El Arbolito Xalostoc'	,	'cp' =>	'55418'   	]	,
[	'nombre' =>	'El Cardonal Xalostoc'	,	'cp' =>	'55418'   	]	,
[	'nombre' =>	'El Nardo'	,	'cp' =>	'55418'   	]	,
[	'nombre' =>	'Esfuerzo Nacional'	,	'cp' =>	'55418'   	]	,
[	'nombre' =>	'Santa María Xalostoc'	,	'cp' =>	'55418'   	]	,
[	'nombre' =>	'Tolotzin V'	,	'cp' =>	'55418'   	]	,
[	'nombre' =>	'5 de Septiembre'	,	'cp' =>	'55419'   	]	,
[	'nombre' =>	'Jardines de Xalostoc'	,	'cp' =>	'55419'   	]	,
[	'nombre' =>	'Las Vegas Xalostoc'	,	'cp' =>	'55420'   	]	,
[	'nombre' =>	'San Francisco Xalostoc'	,	'cp' =>	'55425'   	]	,
[	'nombre' =>	'Ampliación San Francisco Xalostoc'	,	'cp' =>	'55429'   	]	,
[	'nombre' =>	'Prados de Xalostoc'	,	'cp' =>	'55429'   	]	,
[	'nombre' =>	'La Laguna 21'	,	'cp' =>	'55429'   	]	,
[	'nombre' =>	'Melchor Ocampo'	,	'cp' =>	'55430'   	]	,
[	'nombre' =>	'Villas de Guadalupe Xalostoc'	,	'cp' =>	'55430'   	]	,
[	'nombre' =>	'Benito Juárez Xalostoc'	,	'cp' =>	'55430'   	]	,
[	'nombre' =>	'Rustica Xalostoc'	,	'cp' =>	'55430'   	]	,
[	'nombre' =>	'Viveros de Xalostoc'	,	'cp' =>	'55450'   	]	,
[	'nombre' =>	'Ampliación San José Xalostoc'	,	'cp' =>	'55450'   	]	,
[	'nombre' =>	'Parque Industrial Xalostoc'	,	'cp' =>	'55458'   	]	,
[	'nombre' =>	'Urbana Ixhuatepec'	,	'cp' =>	'55459'   	]	,
[	'nombre' =>	'El Salado'	,	'cp' =>	'55490'   	]	,
[	'nombre' =>	'San José Xalostoc'	,	'cp' =>	'55490'   	]	,
[	'nombre' =>	'Ampliación San Miguel Xalostoc'	,	'cp' =>	'55490'   	]	,
[	'nombre' =>	'Altavilla'	,	'cp' =>	'55498'   	]	,
[	'nombre' =>	'San Miguel Xalostoc'	,	'cp' =>	'55500'   	]	,
[	'nombre' =>	'Santa María Tulpetlac'	,	'cp' =>	'55506'   	]	,
[	'nombre' =>	'Aldeas I'	,	'cp' =>	'55507'   	]	,
[	'nombre' =>	'Aldeas II'	,	'cp' =>	'55508'   	]	,
[	'nombre' =>	'Nieves'	,	'cp' =>	'55508'   	]	,
[	'nombre' =>	'ISSEMYM'	,	'cp' =>	'55509'   	]	,
[	'nombre' =>	'Santa María Tulpetlac'	,	'cp' =>	'55509'   	]	,
[	'nombre' =>	'Ecatepec las Fuentes'	,	'cp' =>	'55510'   	]	,
[	'nombre' =>	'El Charco'	,	'cp' =>	'55510'   	]	,
[	'nombre' =>	'El Chamizalito'	,	'cp' =>	'55510'   	]	,
[	'nombre' =>	'El Charco II'	,	'cp' =>	'55515'   	]	,
[	'nombre' =>	'La Purísima'	,	'cp' =>	'55515'   	]	,
[	'nombre' =>	'Talleres Gráficos'	,	'cp' =>	'55516'   	]	,
[	'nombre' =>	'Cuchilla Lázaro Cárdenas'	,	'cp' =>	'55517'   	]	,
[	'nombre' =>	'Tecuescomac'	,	'cp' =>	'55518'   	]	,
[	'nombre' =>	'Lomas de San Carlos Cantera'	,	'cp' =>	'55518'   	]	,
[	'nombre' =>	'El Ostor'	,	'cp' =>	'55518'   	]	,
[	'nombre' =>	'Xochitenco'	,	'cp' =>	'55519'   	]	,
[	'nombre' =>	'El Parque'	,	'cp' =>	'55519'   	]	,
[	'nombre' =>	'Nueva Rufino Tamayo'	,	'cp' =>	'55520'   	]	,
[	'nombre' =>	'Tepetlac Texalpa'	,	'cp' =>	'55530'   	]	,
[	'nombre' =>	'La Nopalera 2a. Sección Tulpetlac'	,	'cp' =>	'55530'   	]	,
[	'nombre' =>	'Lomas Verdes Tlaljuyaca'	,	'cp' =>	'55530'   	]	,
[	'nombre' =>	'Margarita Maza de Juárez'	,	'cp' =>	'55530'   	]	,
[	'nombre' =>	'Buenos Aires'	,	'cp' =>	'55540'   	]	,
[	'nombre' =>	'El Rosal'	,	'cp' =>	'55540'   	]	,
[	'nombre' =>	'Mexihuiloya'	,	'cp' =>	'55540'   	]	,
[	'nombre' =>	'El Almarcigo Norte'	,	'cp' =>	'55547'   	]	,
[	'nombre' =>	'El Almarcigo Sur'	,	'cp' =>	'55548'   	]	,
[	'nombre' =>	'Ampliación Almarcigo'	,	'cp' =>	'55548'   	]	,
[	'nombre' =>	'Texalpa'	,	'cp' =>	'55548'   	]	,
[	'nombre' =>	'Benito Juárez 1ra Sección'	,	'cp' =>	'55549'  	]	,

];
        
foreach ($colonias as &$colonia) {
    // Agregar 'Ecatepec' en el campo 'municipio'
    $colonia['municipio'] = 'Ecatepec';

    // Agregar 'Estado de México' en el campo 'estado'
    $colonia['estado'] = 'Estado de México';
}

// Insertar los datos en la base de datos
DB::table('colonias')->insert($colonias);
    }
}
