<?php

namespace Database\Seeders;

use App\Models\Giro;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GiroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        $giros = [
            [	'descripcion' => '	ABARROTES	',],
            [	'descripcion' => '	ACONDICIONAMIENTO FISICO	',],
            [	'descripcion' => '	AGENTES AJUSTADORES	',],
            [	'descripcion' => '	ALAMBRE Y RESORTES	',],
            [	'descripcion' => '	ALIMENTOS	',],
            [	'descripcion' => '	ALQUILADORA	',],
            [	'descripcion' => '	APICULTURA	',],
            [	'descripcion' => '	ARTICULOS DEPORTIVOS	',],
            [	'descripcion' => '	ARTICULOS PARA EL HOGAR	',],
            [	'descripcion' => '	ARTICULOS USADOS	',],
            [	'descripcion' => '	ASERRADERO	',],
            [	'descripcion' => '	ASOCIACIONES	',],
            [	'descripcion' => '	AUTOMOTRIZ	',],
            [	'descripcion' => '	BALEROS Y RODAMIENTOS	',],
            [	'descripcion' => '	BAÑOS	',],
            [	'descripcion' => '	BASCULAS	',],
            [	'descripcion' => '	BEBIDAS	',],
            [	'descripcion' => '	BICICLETAS	',],
            [	'descripcion' => '	BOLSOS Y MALETAS	',],
            [	'descripcion' => '	BONETERIA	',],
            [	'descripcion' => '	CALL CENTER	',],
            [	'descripcion' => '	CARPINTERIA	',],
            [	'descripcion' => '	CARTON Y PAPEL	',],
            [	'descripcion' => '	CASAS DE EMPEÑO	',],
            [	'descripcion' => '	CERRAJERIA	',],
            [	'descripcion' => '	COLCHONES	',],
            [	'descripcion' => '	COMERCIALIZDORA	',],
            [	'descripcion' => '	COMIDA	',],
            [	'descripcion' => '	COMPUTACION	',],
            [	'descripcion' => '	COMUNICACIONES	',],
            [	'descripcion' => '	CONSTRUCCIÓN	',],
            [	'descripcion' => '	CONSULTORIA	',],
            [	'descripcion' => '	CONTABILIDAD	',],
            [	'descripcion' => '	CONTRATACION DE PERSONAL	',],
            [	'descripcion' => '	COPIAS	',],
            [	'descripcion' => '	CORDELES	',],
            [	'descripcion' => '	CORPORATIVOS	',],
            [	'descripcion' => '	COSTALES	',],
            [	'descripcion' => '	CUIDADO PERSONAL	',],
            [	'descripcion' => '	CULTIVO	',],
            [	'descripcion' => '	CURTIDO	',],
            [	'descripcion' => '	DESECHABLES	',],
            [	'descripcion' => '	DESECHOS	',],
            [	'descripcion' => '	DISEÑO	',],
            [	'descripcion' => '	EDITORIAL	',],
            [	'descripcion' => '	EDUCACION	',],
            [	'descripcion' => '	ELECTRICOS	',],
            [	'descripcion' => '	ELECTRONICA	',],
            [	'descripcion' => '	EMPAQUETADO	',],
            [	'descripcion' => '	ENTRETENIMIENTO	',],
            [	'descripcion' => '	ENVASES	',],
            [	'descripcion' => '	EQUIPOS DE MEDICIÓN	',],
            [	'descripcion' => '	ESTACIONAMIENTO	',],
            [	'descripcion' => '	ESTETICAS	',],
            [	'descripcion' => '	FABRICACION DE MEDIOS MAGNETICOS Y OPTICOS	',],
            [	'descripcion' => '	FABRICACIÓN DE TANQUES	',],
            [	'descripcion' => '	FABRICACIÓN DE TORNILLOS	',],
            [	'descripcion' => '	FABRICACIÓN DE UTENCILIOS DE COCINA	',],
            [	'descripcion' => '	FABRICACIÓN DE VALVULAS	',],
            [	'descripcion' => '	FABRICACIÓN DE VELAS	',],
            [	'descripcion' => '	FARMACIA	',],
            [	'descripcion' => '	FERRETERIA	',],
            [	'descripcion' => '	FERTILIZANTES	',],
            [	'descripcion' => '	FINANCIAMIENTO	',],
            [	'descripcion' => '	FLORERIA	',],
            [	'descripcion' => '	FOTOGRAFIA	',],
            [	'descripcion' => '	FRIBRA DE VIDRIO	',],
            [	'descripcion' => '	FUMIGACION	',],
            [	'descripcion' => '	GRANJAS	',],
            [	'descripcion' => '	HERRERIA	',],
            [	'descripcion' => '	HIELO	',],
            [	'descripcion' => '	HOSPEDAJE	',],
            [	'descripcion' => '	ILUMINACION	',],
            [	'descripcion' => '	INMOBILIARIA	',],
            [	'descripcion' => '	INSTALACION DE AIRE ACONDICIONADO	',],
            [	'descripcion' => '	INSTALACIONES ELECTRICAS	',],
            [	'descripcion' => '	INSTALACIONES HIDROSANITARIAS Y DE GAS	',],
            [	'descripcion' => '	INVERNADEROS Y VIVEROS	',],
            [	'descripcion' => '	INVESTIGACIÓN DE MERCADO	',],
            [	'descripcion' => '	JARCERIA	',],
            [	'descripcion' => '	JARDINERIA	',],
            [	'descripcion' => '	JOYERIA Y RELOJES	',],
            [	'descripcion' => '	JUEGOS Y SORTEOS	',],
            [	'descripcion' => '	LAVANDERIA Y TINTORERIA	',],
            [	'descripcion' => '	LIMPIEZA	',],
            [	'descripcion' => '	MADERA	',],
            [	'descripcion' => '	MANTENIMIENTO	',],
            [	'descripcion' => '	MANUFACTURA	',],
            [	'descripcion' => '	MAQUINADO	',],
            [	'descripcion' => '	MAQUINARIA	',],
            [	'descripcion' => '	MASCOTAS	',],
            [	'descripcion' => '	MATERIAL ELECTRICO	',],
            [	'descripcion' => '	MATERIAL METALICO	',],
            [	'descripcion' => '	MATERIALES TRENZABLES	',],
            [	'descripcion' => '	MATERIAS PRIMAS	',],
            [	'descripcion' => '	MENSAJERIA	',],
            [	'descripcion' => '	MERCERIA Y BONETERIA	',],
            [	'descripcion' => '	METALISTERIA	',],
            [	'descripcion' => '	MINERALES NO METALICOS	',],
            [	'descripcion' => '	MOTOCICLETAS	',],
            [	'descripcion' => '	MUEBLES	',],
            [	'descripcion' => '	NOTARIA	',],
            [	'descripcion' => '	ORFEBRERIA Y JOYERIA	',],
            [	'descripcion' => '	ORIENTACION PROFESIONAL	',],
            [	'descripcion' => '	PALETERIA	',],
            [	'descripcion' => '	PANADERIA	',],
            [	'descripcion' => '	PAPELERIA	',],
            [	'descripcion' => '	PERFUMERIA Y COSMETICOS	',],
            [	'descripcion' => '	PINTURAS	',],
            [	'descripcion' => '	PROMOTORES	',],
            [	'descripcion' => '	PSICULTURA Y ACUICULTURA	',],
            [	'descripcion' => '	PUBLICIDAD	',],
            [	'descripcion' => '	PURIFICADORA	',],
            [	'descripcion' => '	RASTRO	',],
            [	'descripcion' => '	REFRACTARIOS	',],
            [	'descripcion' => '	REFUGIOS TEMPORALES	',],
            [	'descripcion' => '	REGALOS	',],
            [	'descripcion' => '	RELIGIOSOS	',],
            [	'descripcion' => '	REPARACIÓN DE BICICLETAS	',],
            [	'descripcion' => '	REPARACION Y MANTENIMIENTO DE EQUIPO ELECTRONICO	',],
            [	'descripcion' => '	REPARACIÓN Y MANTENIMIENTO DE MAQUINARIA	',],
            [	'descripcion' => '	REPARACIONES DEL HOGAR	',],
            [	'descripcion' => '	REPARADORA DE CALZADO	',],
            [	'descripcion' => '	ROPA	',],
            [	'descripcion' => '	ROPA Y CALZADO	',],
            [	'descripcion' => '	SALUD PERSONAL	',],
            [	'descripcion' => '	SEGURIDAD	',],
            [	'descripcion' => '	SEMILLAS Y CHILES 	',],
            [	'descripcion' => '	SERVICIOS ADUANALES	',],
            [	'descripcion' => '	SERVICIOS FINANCIEROS	',],
            [	'descripcion' => '	SERVICIOS FUNERARIOS	',],
            [	'descripcion' => '	SERVICIOS SECRETARIALES	',],
            [	'descripcion' => '	SISTEMAS	',],
            [	'descripcion' => '	SUPERVISION DE OBRA	',],
            [	'descripcion' => '	TABAQUERIA	',],
            [	'descripcion' => '	TAPICERIA	',],
            [	'descripcion' => '	TELAS	',],
            [	'descripcion' => '	TOPOGRAFIA	',],
            [	'descripcion' => '	TRADUCTORES	',],
            [	'descripcion' => '	TRANSPORTE	',],
            [	'descripcion' => '	TRATAMIENTO DE METALES	',],
            [	'descripcion' => '	VETERINARIA	',],
            [	'descripcion' => '	VIDRIO	',],

        ];

        foreach ($giros as $giro) {
            DB::table('giros')->insert($giro);
        }
    }
}
